events { 
    worker_connections 1024; 
}

http {
    # Definimos el grupo de servidores internos
    # Al estar dockerizados, Docker DNS resolverá "microservicio-proyectos" 
    # a las múltiples IPs de todas las réplicas activas.
    upstream proyectos_backend {
        server microservicio-proyectos:4001;
    }

    server {
        listen 4001;

        # Balanceo de cargas en modo Round Robin por defecto
        location / {
            proxy_pass http://proyectos_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
